<?php

// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB

$databaseDialect = "mysql";

$databaseHostname = "127.0.0.1";

$databasePort = 3306;

$databaseName = "aen";

$databaseUsername = "aen";

$databasePassword = "aen";